#Static configuration of the server.
server.port=9999
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
spring.datasource.username=Manager
spring.datasource.password=temp001
spring.datasource.platform=oracle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#Print the debug info. This is the logging level.
#This info is used to fine-tune the program.
logging.level.org.hibernate.SQL=DEBUG
#When TRACE is enabled in Spring Data JPA, it prints info about hibernate actions/statements.
#Useful for debugging the programs.
logging.level.org.hibernate.type=TRACE
#mentioning the location where the view files(html files) are present.
spring.mvc.view.prefix=/resources/templates
spring.mvc.view.suffix=.html
#spring.thymeleaf.prefix=classpath:/resources/templates
#spring.thymeleaf.suffx=.html
 
#m - minute, h- hours, s - seconds, ms - milliseconds
server.servlet.session.timeout=1m
spring.main.allow-circular-references=true
 
 